// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfVPm7dCtayQjwsjDhKgdPbN0_eW_qT2I',
    appId: '1:888830541138:web:e892a2b0ac3680de2ece8b',
    messagingSenderId: '888830541138',
    projectId: 'tikitok-bbc98',
    authDomain: 'tikitok-bbc98.firebaseapp.com',
    storageBucket: 'tikitok-bbc98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSepWKXU54xCKmJ_igxdYAFUl71p7Rmqk',
    appId: '1:888830541138:android:9a957a8a3f3bf45b2ece8b',
    messagingSenderId: '888830541138',
    projectId: 'tikitok-bbc98',
    storageBucket: 'tikitok-bbc98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QGIWp0AbDsY-5OMFN0uUiCxle40fQTQ',
    appId: '1:888830541138:ios:f334486669c355f22ece8b',
    messagingSenderId: '888830541138',
    projectId: 'tikitok-bbc98',
    storageBucket: 'tikitok-bbc98.appspot.com',
    iosBundleId: 'com.example.tikitok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QGIWp0AbDsY-5OMFN0uUiCxle40fQTQ',
    appId: '1:888830541138:ios:e408987e320f2e672ece8b',
    messagingSenderId: '888830541138',
    projectId: 'tikitok-bbc98',
    storageBucket: 'tikitok-bbc98.appspot.com',
    iosBundleId: 'com.example.tikitok.RunnerTests',
  );
}
